TRAIN_DATA = [
			("exit",{'entities':[(0,4,'QUIT')]}),
			("quit",{'entities':[(0,4,'QUIT')]}),			
			("hello",{'entities':[(0,5,'GREET')]}),
		    ("hi",{'entities':[(0,2,'GREET')]}),
		    ("namaste",{'entities':[(0,7,'GREET')]}),
		    ("yo, Nebula ",{'entities':[(0,2,'GREET'),(4,10,'PERSON')]}),
		    ("Nebula namaste",{'entities':[(7,14,'GREET'),(0,6,'PERSON')]}),			
			('who is allen maharjan',{'entities':[(7,21,'PERSON'),(0,3,'QUESTION')]} ),
		    ("allen maharjan", {'entities': [(0, 14, 'PERSON')]}),
			('who is saugat rai',{'entities':[(7,17,'PERSON'),(0,3,'QUESTION')]} ),
			('who is kancha bhai manandhar',{'entities':[(7,28,'PERSON'),(0,3,'QUESTION')]} ),
			("who is bibhuti ranjan jha",{'entities':[(7,25,'PERSON')]}),
			("where can I meet br jha",{'entities':[(17,23,'PERSON')]}),
			("how can I contact db gurung",{'entities':[(18,28,'PERSON')]}),
			('who is the hod of the Department of Environmental Science and Engineering',{'entities':[(11,14,'position'),(22,73,'program')]}),
			('who is hod of Department of Environmental Science and Engineering',{'entities':[(7,10,'position'),(14,65,'program')]}),
			('who is the hod of DOESE',{'entities':[(11,14,'position'),(18,23,'program')]}),
			('who is the hod of the DOESE',{'entities':[(11,14,'position'),(22,27,'program')]}),
			('who is the head of department of DOESE',{'entities':[(11,29,'position'),(33,38,'program')]}),
			('who is head of department of the DOESE',{'entities':[(7,25,'position'),(33,38,'program')]}),
			('who is the head of department of Department of Environmental Science and Engineering',{'entities':[(11,29,'position'),(33,84,'program')]}),
			('who is head of department of the Department of Environmental Science and Engineering',{'entities':[(7,25,'position'),(33,84,'program')]}),
			('where can i meet hod of DOESE',{'entities':[(17,20,'position'),(24,29,'program')]}),
			('where can i meet head of department of DOESE',{'entities':[(17,35,'position'),(39,44,'program')]}),
			('where can i meet the head of department of DOESE',{'entities':[(21,39,'position'),(43,48,'program')]}),
			('where can i meet the head of department of the DOESE',{'entities':[(21,39,'position'),(47,52,'program')]}),
			('where is Nepal Investment Bank',{'entities':[(9,30,'BANK'),(0,5,'QUESTION')]} ),
			('how can I get to NIBL',{'entities':[(17,21,'BANK'),(0,3,'QUESTION')]} ),
			('how much do I have to pay in Investment Bank',{'entities':[(29,44,'BANK'),(0,3,'QUESTION')]} ),
			('is there a photocopy machine near Bank',{'entities':[(34,38,'BANK'),(0,8,'QUESTION')]} ),
			('who are you',{'entities':[(8,11,'PERSON')]} ),
			('what are you',{'entities':[(9,12,'PERSON')]} ),
			('how are you',{'entities':[(8,11,'PERSON')]} ),
		]
